language: node_js
node_js:
  - "18"
cache:
  directories:
    - node_modules

deploy:
  provider: pages
  edge: true
  strategy: git
  token: $GITHUB_TOKEN
  local_dir: build
  keep_history: false
  on:
    branch: main

